### ISSUE TITLE
💾 GitHub Actions Cacheでサムネイル取得を永続化

### ISSUE THREAD

**Issue by unsolublesugar** [unsolublesugar/daily-tech-news#25]
## 概要
GitHub Actions Cacheを活用してサムネイル取得結果を永続化し、実行時間をさらに短縮する

## 背景・課題
- 現在は毎回全サムネイルを再取得（約100秒）
- Issue #24の並列化で10秒に短縮予定だが、さらなる最適化が可能
- GitHub Actionsの実行環境は毎回クリーンなため、前回の取得結果が活用できない
- 同じ記事のサムネイルを繰り返し取得するのは非効率

## 期待される改善効果
```
現在：      毎日100秒（全取得）
並列化後：   毎日10秒（並列取得）
キャッシュ後： 1日目10秒 → 2日目3秒 → 3日目1秒 🚀
```

### 1. GitHub Actions Workflow修正
```yaml
# .github/workflows/update-news.yml
name: Update Daily Tech News
on:
  schedule:
    - cron: '0 22 * * *'  # JST 7:00
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    # サムネイルキャッシュの復元
    - name: Restore thumbnail cache
      uses: actions/cache@v3
      with:
        path: thumbnail_cache.json
        key: thumbnails-v1-${{ github.run_number }}
        restore-keys: |
          thumbnails-v1-
          
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Update news with cache
      run: python fetch_news.py
      
    # キャッシュは自動保存される
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages
```

### 2. キャッシュ管理クラスの実装
```python
import json
import datetime
from pathlib import Path
from typing import Optional, Dict

class ThumbnailCache:
    def __init__(self, cache_file="thumbnail_cache.json", cache_days=7):
        self.cache_file = Path(cache_file)
        self.cache_days = cache_days
        self.cache = self._load_cache()
        print(f"Loaded thumbnail cache with {len(self.cache)} entries")
    
    def _load_cache(self) -> Dict:
        """GitHub Actions Cacheから復元されたファイルを読み込み"""
        if self.cache_file.exists():
            try:
                with open(self.cache_file, 'r', encoding='utf-8') as f:
                    cache_data = json.load(f)
                    print(f"Cache file loaded: {len(cache_data)} entries")
                    return cache_data
            except (json.JSONDecodeError, IOError) as e:
                print(f"Cache file corrupted: {e}, starting fresh")
                return {}
        else:
            print("No cache file found, starting fresh")
            return {}
    
    def get(self, url: str) -> Optional[str]:
        """キャッシュから取得（期限切れチェック付き）"""
        if url not in self.cache:
            return None
            
        entry = self.cache[url]
        expires_at = datetime.datetime.fromisoformat(entry['expires_at'])
        
        if datetime.datetime.now() > expires_at:
            # 期限切れ → 削除してNoneを返す
            del self.cache[url]
            return None
            
        return entry['thumbnail_url']
    
    def set(self, url: str, thumbnail_url: Optional[str]):
        """新しい結果をキャッシュに保存"""
        now = datetime.datetime.now()
        expires = now + datetime.timedelta(days=self.cache_days)
        
        self.cache[url] = {
            'thumbnail_url': thumbnail_url,
            'cached_at': now.isoformat(),
            'expires_at': expires.isoformat()
        }
    
    def save(self):
        """キャッシュファイルを保存（GitHub Actions Cacheに含まれる）"""
        try:
            with open(self.cache_file, 'w', encoding='utf-8') as f:
                json.dump(self.cache, f, ensure_ascii=False, indent=2)
            print(f"Cache saved: {len(self.cache)} entries")
        except IOError as e:
            print(f"Failed to save cache: {e}")
    
    def cleanup_expired(self):
        """期限切れエントリの削除"""
        now = datetime.datetime.now()
        expired_urls = []
        
        for url, entry in list(self.cache.items()):
            expires_at = datetime.datetime.fromisoformat(entry['expires_at'])
            if now > expires_at:
                expired_urls.append(url)
                del self.cache[url]
                
        if expired_urls:
            print(f"Cleaned up {len(expired_urls)} expired cache entries")
    
    def stats(self):
        """キャッシュ統計を返す"""
        total = len(self.cache)
        has_thumbnail = sum(1 for entry in self.cache.values() 
                          if entry['thumbnail_url'] is not None)
        no_thumbnail = total - has_thumbnail
        
        return {
            'total_entries': total,
            'with_thumbnail': has_thumbnail,
            'without_thumbnail': no_thumbnail,
            'success_rate': (has_thumbnail / total * 100) if total > 0 else 0
        }
```

### 3. 並列処理とキャッシュの統合
```python
def fetch_all_thumbnails_with_cache(all_entries, max_workers=10):
    """GitHub Actions Cache機能付き並列サムネイル取得"""
    cache = ThumbnailCache()
    
    # 期限切れエントリのクリーンアップ
    cache.cleanup_expired()
    
    # 全URLリストを作成
    all_urls = []
    for entries in all_entries.values():
        all_urls.extend([entry.link for entry in entries])
    
    # キャッシュヒット/ミスの分類
    cached_results = {}
    urls_to_fetch = []
    
    print("Checking GitHub Actions cache...")
    for url in all_urls:
        cached_thumbnail = cache.get(url)
        if cached_thumbnail is not None:
            cached_results[url] = cached_thumbnail
        else:
            urls_to_fetch.append(url)
    
    cache_hit_rate = len(cached_results) / len(all_urls) * 100
    print(f"Cache hit rate: {cache_hit_rate:.1f}% ({len(cached_results)}/{len(all_urls)})")
    
    if urls_to_fetch:
        print(f"Fetching {len(urls_to_fetch)} new thumbnails in parallel...")
        
        with ThreadPoolExecutor(max_workers=max_workers) as executor:
            future_to_url = {
                executor.submit(get_article_thumbnail, url): url 
                for url in urls_to_fetch
            }
            
            completed = 0
            total_new = len(urls_to_fetch)
            
            for future in concurrent.futures.as_completed(future_to_url):
                url = future_to_url[future]
                completed += 1
                
                try:
                    thumbnail_url = future.result(timeout=15)
                    cached_results[url] = thumbnail_url
                    cache.set(url, thumbnail_url)
                    print(f"Progress: {completed}/{total_new} new thumbnails fetched")
                except Exception as e:
                    print(f"Error fetching thumbnail for {url}: {e}")
                    cached_results[url] = None
                    cache.set(url, None)  # エラー結果もキャッシュ
    
    # キャッシュファイルを保存（GitHub Actions Cacheに含まれる）
    cache.save()
    
    # 統計表示
    stats = cache.stats()
    print(f"Cache stats: {stats['total_entries']} entries, "
          f"success rate: {stats['success_rate']:.1f}%")
    
    return cached_results
```

### 4. メイン処理での使用
```python
if __name__ == "__main__":
    start_time = time.time()
    
    # RSS取得と重複除去
    all_entries = {}
    for name, feed_info in FEEDS.items():
        print(f"Fetching entries from {name}...")
        entries = fetch_feed_entries(feed_info["url"])
        all_entries[name] = entries
    
    all_entries = deduplicate_urls_across_feeds(all_entries)
    
    # 🚀 キャッシュ機能付き並列サムネイル取得
    thumbnails = fetch_all_thumbnails_with_cache(all_entries)
    
    # 各生成処理
    markdown_content = generate_markdown(all_entries, FEEDS, today.isoformat())
    html_content = generate_html(all_entries, FEEDS, today.isoformat(), thumbnails)
    rss_feed = generate_rss_feed(all_entries, FEEDS, today)
    
    # ファイル保存処理...
    
    total_time = time.time() - start_time
    print(f"Total execution time: {total_time:.2f} seconds")
```

### キャッシュキー戦略
```yaml
key: thumbnails-v1-${{ github.run_number }}
restore-keys: |
  thumbnails-v1-
```

- **primary key**: 実行番号付きでユニーク
- **restore-keys**: 最新のキャッシュを復元
- **バージョン管理**: `v1` でキャッシュ形式変更時の管理

### 容量・期限制限
- **最大容量**: 10GB（十分すぎる）
- **保持期間**: 7日間（未使用の場合削除）
- **アクセス制限**: 同じリポジトリ内のWorkflowのみ

## 受け入れ条件
- [ ] GitHub Actions Workflowでキャッシュが正常に動作する
- [ ] 初回実行後、2回目以降の実行時間が大幅短縮される
- [ ] キャッシュヒット率が適切に表示される
- [ ] 期限切れエントリの自動クリーンアップが機能する
- [ ] エラー発生時もキャッシュが破損しない
- [ ] 手動実行（workflow_dispatch）でも正常に動作する
- [ ] 既存の機能に影響がない

## 期待される実行時間の変化
```
実装前：
  毎日100秒（全サムネイル取得）

並列化実装後（Issue #24）：
  毎日10秒（並列取得）

キャッシュ実装後：
  1日目: 10秒（初回キャッシュ構築）
  2日目: 3秒（新記事30%程度）
  3日目: 2秒（新記事20%程度）
  1週間後: 1秒（ほぼ全てキャッシュヒット）🚀
```

## 技術的考慮事項
- GitHub Actions Cacheの容量制限（10GB）
- キャッシュキーの命名戦略
- restore-keysによるフォールバック
- キャッシュファイルの破損対策
- 期限切れエントリの効率的な管理
- 複数並列実行時の競合状態対策

## 将来的な拡張案
- キャッシュ統計のダッシュボード表示
- 段階的キャッシュ更新（重要フィード優先）
- キャッシュウォームアップ機能
- 異なる環境（開発/本番）でのキャッシュ分離
- キャッシュサイズの自動最適化

## 前提条件
- Issue #24（サムネイル並列化）の完了
- GitHub Actions環境での動作確認
- requirements.txtの更新（必要に応じて）
